#!/usr/bin/env bash

# Run migrations.
php /var/www/html/artisan migrate --force

# Cache config and routes.
if [[ "${IS_LOCAL}" != "true" ]]; then
    php /var/www/html/artisan config:cache
    php /var/www/html/artisan route:cache
fi

# Start supervisor.
/usr/bin/supervisord
