language: php

php:
  - 7.2

services:
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - sourceline: deb https://packages.cloudfoundry.org/debian stable main
        key_url: https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key
      - sourceline: deb https://artifacts.elastic.co/packages/6.x/apt stable main
        key_url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    packages:
      - mysql-server
      - cf-cli
      - elasticsearch

dist: trusty

sudo: required

branches:
  only:
    - master
    - develop

cache:
  directories:
    - vendor
    - node_modules

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D27D666CD88E42B4
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5733FEC050C212B6

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run dev

before_script:
  - sudo -i service elasticsearch start
  - sleep 10 # Needed to give Elasticsearch time to setup
  - mysql -e 'create database ck_testing;'
  - php artisan migrate --force
  - php artisan passport:keys

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    repo: RoyalBoroughKingston/ck-api
    branch: develop

notifications:
  slack:
    secure: "UYQa59/m3YMI/8Ycdsh6B6fc11k9Qy0ZJG2VovLwLhZLPZiN+wCvt70cqvGwSDvDLIhU2QgVMe7/oTl2vrHpJNdkTKuy/wbVrJkBK9q2/i/WF8YxCdrfsXFphXF3M90OjblvT3AHRakvoNGN4ChV3VDXWr7hG3+leJSBWXRszvztlGZ2ag6xxDqglY5rj+xVQh2rjAIEVvwr8BahLLpYWYl+tcKzHrK0X1tXHXf0VqdJI29Y4GggyroCSknLmD40c2Bcr4BwHmBkcGBCFIO0cIAEV2qxjejCxCoOVFlucqKcR4BH0lkf8FmRhuhgBD32mCFa7zYXUNmwj5KaIMsvZDI2wAQiIR/zYUeqxRriij20ag7IpaTyJY2VNXbUtb+/tHAg/Zd7MHhdgIjRSbrPnaFKz7920HvPcUXLFr9saBC+DuI9ratqWwhAoi2UtAFgfbx/oA8Ztzp9bpZoYf6D/4XWeKt8p3o1dhbDng1j6uZPSyhxGJ8EuiWu9iiyd9MbZU2A9K3Qi7dHs9m7d5wVHS0yf0N4jbiTbO/5G4/ZS71D50lfeAyjTBlfLhtHengVqbl5JVgXnW/MgSxawJPdYxv4CeiWrjvzn4VtPvKFtZUVQ9EeDcMD7PVPwjgPuMY5AeLNSll43jMU8j/wqrM0GhfzHqvy52JijV0BmPAvS/I="
