language: php

php:
  - 7.2

services:
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - sourceline: deb https://packages.cloudfoundry.org/debian stable main
        key_url: https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key
    packages:
      - mysql-server
      - cf-cli

dist: trusty

sudo: required

branches:
  only:
    - master
    - develop

cache:
  directories:
    - vendor
    - node_modules

install:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run dev

before_script:
  - mysql -e 'create database ck_testing;'
  - php artisan migrate --force --seed
  - php artisan passport:keys

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    repo: RoyalBoroughKingston/ck-api
    branch: develop

notifications:
  slack:
    secure: "GseL/cFC3A9l0kOYM05rGgv5FnLJYyJVETmcFrOfBBvdsr6aMnyEcg/NtLxElgkqS/yGgaUWG9xc/5B/HuBuVNIPfSTwYVMFctQw2uhdcRVjqXB8Z/+g6PZM9p76MgbXOGAyNjhhPgjaB7m6A7FC4U1YpkGWTfi7cuWydiqLAd/RkOTqnJyNB8pKMkdtj7myAwN0SHmbEPjVxORltvM7vJzgY9GFwu8m/JoCCEL3mjemIElvhQFz29WQGio/0AP1W25INaCHQ+aKVXuah4rHIYT+jYwz2n3C887ivG59a5tJWiWwJioQwdPikdCZVS79wU0MFooi1IrLYU8B8ecN+FVnKOMvrZItSKEHuG9n4KFy74aLx9swT24JynUXtH9oVJgz93irE1hyZapJNliKc8pcavL3hahQr7ITDsND6gDY8TFw1G7o2V7Bwu/ELuAnUkCh979IDusb6zE2p2bLDW/LSWK4U2wydw7kBpNUqvs2YgX7MK6SP12IdF+kYk1JSVk8MLucsg0J9xpusfCDMqUE0n4snFIB2nmRiFmU4+1TT7JqBgiaLRk4iDH8ZDp3A9X67Ekc7GNzc7qiT9ui7u1XCfRjSronwdVnylmSm6jAWdcYtCs1Rw1P6l+iyACsMMJ1WUX3Zu5lMheC9qZPQLYRcl0Ur6J1BwOLZ3egP/k="
