if: tag IS blank
branches:
  only:
    - master
    - develop

language: python
python:
  - '3.8'

services:
  - docker

before_install:
  - echo "Installing Docker"
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - echo "Docker installed"

before_script:
  - sudo service mysql stop
  - ./develop build
  - ./develop up -d
  - ./develop npm ci
  - ./develop npm run dev
  - ./develop composer install
  - ./develop run --rm -T app mv .env.example .env
  - ./develop artisan key:generate
  - ./develop artisan passport:keys

script:
  - ./develop composer test:style
  - ./develop composer test:unit

after_failure:
  - cat storage/logs/testing.log

before_deploy:
  - echo "Compiling assets for production..."
  - ./develop npm run prod

  - echo "Installing AWS CLI..."
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install -i /usr/local/aws -b /usr/local/bin

  - echo "Installing CloudFoundry CLI..."
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update && sudo apt-get install -y --allow-unauthenticated cf-cli

deploy:
  - provider: script
    script: ./.travis/deploy
    skip_cleanup: true
    on:
      branch:
        - master
        - develop
