version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
permissions:
  - object: /var/www/html
    user: apache
    group: apache
  - object: /var/www/html/bootstrap/cache
    user: apache
    group: apache
    mode: 777
  - object: /var/www/html/storage
    user: apache
    group: apache
    mode: 777
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
