version: '3'

services:
  app:
    ports:
      - 80:80
    networks:
      - kingston-net

  scheduler:
    depends_on:
      - app
    networks:
      - kingston-net

  queue-worker:
    depends_on:
      - app
      - redis
    networks:
      - kingston-net

  node:
    networks:
      - kingston-net

  mysql:
    ports:
      - 3306:3306
    volumes:
      - kingston-mysql-data:/var/lib/mysql
    networks:
      - kingston-net

  mysql-testing:
    networks:
      - kingston-net

  redis:
    volumes:
      - kingston-redis-data:/data
    networks:
      - kingston-net

  redis-testing:
    networks:
      - kingston-net

  elasticsearch:
    volumes:
      - kingston-elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - kingston-net

volumes:
  kingston-mysql-data:
    driver: local
  kingston-redis-data:
    driver: local
  kingston-elasticsearch-data:
    driver: local
networks:
  kingston-net:
