# Set base image.
FROM node:10.12

# Set maintainer to Ayup Digital.
LABEL maintainer="Ayup Digital"

# Install git for faster package downloads.
RUN apt-get install -y git

# Set the working directory to the project root.
WORKDIR /var/www/html
