update:
  type: object
  required:
    - cms
  properties:
    cms:
      type: object
      required:
        - frontend
      properties:
        frontend:
          type: object
          required:
            - global
            - home
            - terms_and_conditions
            - privacy_policy
            - about
            - contact
            - get_involved
            - favourites
          properties:
            global:
              type: object
              required:
                - footer_title
                - footer_content
                - contact_phone
                - contact_email
                - facebook_handle
                - twitter_handle
              properties:
                footer_title:
                  type: string
                footer_content:
                  type: string
                  format: markdown
                contact_phone:
                  type: string
                contact_email:
                  type: string
                facebook_handle:
                  type: string
                twitter_handle:
                  type: string
            home:
              type: object
              required:
                - search_title
                - categories_title
                - personas_title
                - personas_content
              properties:
                search_title:
                  type: string
                categories_title:
                  type: string
                personas_title:
                  type: string
                personas_content:
                  type: string
                  format: markdown
            terms_and_conditions:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: string
                  format: markdown
            privacy_policy:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: string
                  format: markdown
            about:
              type: object
              required:
                - title
                - content
                - video_url
              properties:
                title:
                  type: string
                content:
                  type: string
                  format: markdown
                video_url:
                  type: string
            contact:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: string
                  format: markdown
            get_involved:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: string
                  format: markdown
            favourites:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: string
                  format: markdown
