openapi: 3.0.1

info:
  title: {{ config('app.name') }} Core API Specification
  description: For using the Core {{ config('app.name') }} API
  version: v1
  contact:
    name: Ayup Digital
    url: https://ayup.agency

servers:
- url: {{ url('/core/v1') }}

paths:
  /audits:
    $ref: /docs/core/paths/audits.yaml#/root
  /audits/{audit}:
    $ref: /docs/core/paths/audits.yaml#/nested

  /collections/categories:
    $ref: /docs/core/paths/category-collections.yaml#/root
  /collections/categories/{category}:
    $ref: /docs/core/paths/category-collections.yaml#/nested

  /collections/personas:
    $ref: /docs/core/paths/persona-collections.yaml#/root
  /collections/personas/{persona}:
    $ref: /docs/core/paths/persona-collections.yaml#/nested
  /collections/personas/{persona}/image.png:
    $ref: /docs/core/paths/persona-collections.yaml#/image

  /locations:
    $ref: /docs/core/paths/locations.yaml#/root
  /locations/{location}:
    $ref: /docs/core/paths/locations.yaml#/nested

  /notifications:
    $ref: /docs/core/paths/notifications.yaml#/root
  /notifications/{notification}:
    $ref: /docs/core/paths/notifications.yaml#/nested

  /organisations:
    $ref: /docs/core/paths/organisations.yaml#/root
  /organisations/{organisation}:
    $ref: /docs/core/paths/organisations.yaml#/nested
  /organisations/{organisation}/logo.png:
    $ref: /docs/core/paths/organisations.yaml#/logo

  /page-feedbacks:
    $ref: /docs/core/paths/page-feedbacks.yaml#/root
  /page-feedbacks/{page_feedback}:
    $ref: /docs/core/paths/page-feedbacks.yaml#/nested

  /referrals:
    $ref: /docs/core/paths/referrals.yaml#/root
  /referrals/{referral}:
    $ref: /docs/core/paths/referrals.yaml#/nested

  /report-schedules:
    $ref: /docs/core/paths/report-schedules.yaml#/root
  /report-schedules/{report_schedule}:
    $ref: /docs/core/paths/report-schedules.yaml#/nested

  /reports:
    $ref: /docs/core/paths/reports.yaml#/root
  /reports/{report}:
    $ref: /docs/core/paths/reports.yaml#/nested
  /reports/{report}/download:
    $ref: /docs/core/paths/reports.yaml#/download

  /search:
    $ref: /docs/core/paths/search.yaml#/root

  /service-locations:
    $ref: /docs/core/paths/service-locations.yaml#/root
  /service-locations/{service_location}:
    $ref: /docs/core/paths/service-locations.yaml#/nested

  /services:
    $ref: /docs/core/paths/services.yaml#/root
  /services/{service}:
    $ref: /docs/core/paths/services.yaml#/nested
  /services/{service}/logo.png:
    $ref: /docs/core/paths/services.yaml#/logo

  /status-updates:
    $ref: /docs/core/paths/status-updates.yaml#/root

  /taxonomies/categories:
    $ref: /docs/core/paths/category-taxonomies.yaml#/root
  /taxonomies/categories/{category}:
    $ref: /docs/core/paths/category-taxonomies.yaml#/nested

  /taxonomies/organisations:
    $ref: /docs/core/paths/organisation-taxonomies.yaml#/root
  /taxonomies/organisations/{organisation}:
    $ref: /docs/core/paths/organisation-taxonomies.yaml#/nested

  /thesaurus:
    $ref: /docs/core/paths/thesaurus.yaml#/root

  /update-requests:
    $ref: /docs/core/paths/update-requests.yaml#/root
  /update-requests/{update_request}:
    $ref: /docs/core/paths/update-requests.yaml#/nested
  /update-requests/{update_request}/approve:
    $ref: /docs/core/paths/update-requests.yaml#/approve

  /users:
    $ref: /docs/core/paths/users.yaml#/root
  /users/{user}:
    $ref: /docs/core/paths/users.yaml#/nested
  /users/{user}/user:
    $ref: /docs/core/paths/users.yaml#/user
  /users/{user}/user/sessions:
    $ref: /docs/core/paths/users.yaml#/sessions

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: {{ url('/oauth/authorize') }}

security:
- OAuth2: []

tags:
- name: Audits
- name: "Collection: Categories"
- name: "Collection: Personas"
- name: Locations
- name: Notifications
- name: Organisations
- name: Page Feedbacks
- name: Referrals
- name: Report Schedules
- name: Reports
- name: Search
- name: Service Locations
- name: Services
- name: Status Updates
- name: "Taxonomy: Categories"
- name: "Taxonomy: Organisations"
- name: Thesaurus
- name: Update Requests
- name: Users

externalDocs:
  description: GitHub Wiki
  url: https://github.com/RoyalBoroughKingston/cwk-api/wiki
